### ISSUE TITLE
Create simple Submarine vessel with two player starts within the vessel. 

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#11]
We just need the vessel environment with the screens, the player starts (#1 and #2). Vessel movement can optionally come in a later issue.

**Comment by rameshvarun** [comment]
Oculus Rift Submarine in Second Life - https://www.youtube.com/watch?v=UuIi7lRjmug

**Comment by austinchambers** [comment]
That's pretty cool! The dead arms seem a bit odd, but it certainly has atmosphere. I'm thinking some of the scenes in Bioshock would be totally awesome in VR.

**Comment by austinchambers** [comment]
Since we're going with the submarine approach, it seems appropriate to narrow the scope here, making this issue about creating the actual vessel itself.

**Comment by rameshvarun** [comment]
Thoughts on this Asset Store model? I purchased this earlier.

![image](https://cloud.githubusercontent.com/assets/889879/6438274/62b678fa-c07c-11e4-8324-c312905d79e1.png)

Link - https://www.assetstore.unity3d.com/en/#!/content/21092
Cons - The texture resolution is pretty low (we may need to retouch it)

**Comment by damlaren** [comment]
I think this would work provided that there is enough room to put two people inside it.

**Comment by damlaren** [comment]
I think this is done, actually. Players start by possessing sub pawns and we dropped the cooperative 2-person-per-sub approach.
