### ISSUE TITLE
Add Mine threats to environment

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#17]
We will add more to the gameplay if there are mine threats that need to be avoided or shot out. This can create a cooperative element, where one player is piloting, and another player is mining the turrets, shooting out the mines. 

We also need to register splash damage due to the proximity of the explosion of the mine. (Effects are in another issue)

**Comment by damlaren** [comment]
I added a blueprint for a homing mine (BP_Mine) which causes damage to any targetable object (an object implementing the empty interface BPI_Targetable; currently just subs and mines). The explosion applies an impulse to objects as well and will push them away.

This means mines can be used to destroy other mines too! Possibly an interesting gameplay mechanic.

Note that mines currently don't discriminate between objects-- any nearby object, including a player sub that laid the mine, can be targeted. We'll either want to discriminate, or only activate the mine after a timer to force the minelayer to speed away.
