### ISSUE TITLE
Display ship damage to the screen. 

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#19]
We need some way to display ship damage, so that the player can address the damage or choose to be more careful.

Simple enhancement possibility is to have damage for different sections (e.g., front, side, and rear).

**Comment by damlaren** [comment]
We could do this, but an easier shortcut may be to have a light inside the sub that changes color from green -> yellow -> red as the sub takes damage. Every time the sub reaches a new damage milestone (goes below X % of total health) it could sound an alarm.

**Comment by damlaren** [comment]
Austin do we still need a separate screen for this or can we close this out?

**Comment by damlaren** [comment]
done
