### ISSUE TITLE
Support for "Unpossessing" an pawn. 

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#20]
When an pawn is unpossessed, the player returns to his body. 
(Later on, we can make it so that the object being controlled by the player plummets to the earth and is destroyed. This can create an interesting situation where you need to wait and/or rebuild a possessable object)

**Comment by damlaren** [comment]
I think I'll work on this next if no one else is?

**Comment by austinchambers** [comment]
David, this one's a bit intermingled with the player character networking. Do you mind if I finish this one up? Should only be a few hours.

**Comment by damlaren** [comment]
OK, that's fine with me. I'll look for something else to work on.

**Comment by austinchambers** [comment]
Fixed with changeset 6c501f6. Removed "Networking" tag, as I think I'll cover that in the other networking issue for screens. 

## BP_Choppa/BP_PuppetScreen Changes:
- It's not too elegant right now, but the BP_Choppa simply stores the last return character and the current controller. We set this prior to possessing (BP_PuppetScreen) and set this to None when we possess back to our return character. 
  ![image](https://cloud.githubusercontent.com/assets/8466736/6430004/de97afee-bfa9-11e4-84fb-c410f7f5351d.png)
  ![image](https://cloud.githubusercontent.com/assets/8466736/6430012/401fd566-bfaa-11e4-8bd6-f330f0c1c2fc.png)

## MyCharacter Changes: 
- There was a bug here with Interactive Objects. When you move immediately from one interactive object to another, you need to simultaneously "Not Look At" (old objecT) and "Look At" (new object). This is why we were having difficult with persistently highlighted screens. This was also a problem with possession because the old screen was blocking all player input. 
  ![image](https://cloud.githubusercontent.com/assets/8466736/6430011/2344b51a-bfaa-11e4-986b-ab8b5d65529e.png)

**Comment by austinchambers** [comment]
Noticed and fixed two other issues: 
1. When you "depossess" the character, it's still looking at stuff. This can cause problems because what it looks it can mess with inputs/highlighting. Added changes to _not_ do the ray casting thing when default character pawn is not possessed. 
![image](https://cloud.githubusercontent.com/assets/8466736/6430052/0fdb5e5e-bfad-11e4-803c-b10a75026853.png)
1. When you "depossess" the choppa, you can be placed right back in front of the screen again. In this instance, it won't be highlighted because the Last Interactive Object was not unset for the character (as we never actually looked away from the screen). Fixed that by nulling it out on possess choppa. 
   ![image](https://cloud.githubusercontent.com/assets/8466736/6430050/023389d4-bfad-11e4-8b5f-aafc4ae85806.png)

**Comment by austinchambers** [comment]
Got rid of hacky "ReturnCharacter" reference in changeset 4d96670
