### ISSUE TITLE
Base Class Blueprint for "Interact-By-Looking" objects

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#21]
There will be lots of different "interact-by-looking" objects. That is, the contextual switching mechanism that enables you to do something special by looking at it (one of the key reasons we benefit from VR). 

Accordingly, to avoid code duplication, we should establish a base blueprint class that can be reused. In short, it will work like this: 
1. PlayerCharacter shoots out a ray. 
2. We get all the objects that support "interact-by-looking" at execute the "LookAt" event. 
3. This causes certain functionality in the respective object (e.g., screens may highlight).

**Comment by austinchambers** [comment]
In Progress

**Comment by damlaren** [comment]
Should we do this, or should we just have the players always seated and switching between different screens to change functionality?

**Comment by austinchambers** [comment]
This is a refactoring issue (it won't change game behavior) -- it'll just help with the implementation of future screens/interactive objects. 

As for your question, I actually imagined the players as being seated. Even so, this look at functionality is still needed to switch screen context.

**Comment by austinchambers** [comment]
Fixed in 45409e6. 

## BP_InteractiveObject

Added BP_InteractiveObject base class. This class handles the highlighting and the player controller switching logic. 
There are 4 functions you should know about: 
1. ConstructionScript (This is where we set DynamicHighlightMesh. In your base class, be sure to choose the mesh you want to highlight and this function auto-handles it). 
![image](https://cloud.githubusercontent.com/assets/8466736/6429839/b967082c-bfa0-11e4-94a6-8ed5ed3c0e0e.png)
2. PlayerLookingAt / PlayerNotLookingAt. Pretty much the same as used to be in BP_PuppetScreen. 
![image](https://cloud.githubusercontent.com/assets/8466736/6429838/b419136a-bfa0-11e4-9418-80e980a92e97.png)
4. RespondToLook. This is the post-lookat function that returns a variable saying whether someone is currently looking at the relevant player controller (typically, this is overridden by the derived class). 
![image](https://cloud.githubusercontent.com/assets/8466736/6429836/a8071d24-bfa0-11e4-9d7e-1e91a244dcd9.png)

## BP_PuppetScreen: 

Key changes
1. Added "Set Input Control" function. This handles setting/changing inputs on look events. 
![image](https://cloud.githubusercontent.com/assets/8466736/6429844/fe49855a-bfa0-11e4-83e2-5d9afa820736.png)
1. Handled the "EventRespondToLook" event from BP_InteractiveObject. It sets input then text visibility
   ![image](https://cloud.githubusercontent.com/assets/8466736/6429843/f8233af4-bfa0-11e4-8332-060db02ac964.png)

## MyCharacter

Everything is pretty much the same except that we're hunting "InteractiveObjects" with rays instead of only puppet screens.
