### ISSUE TITLE
Make a movable ship

### ISSUE THREAD

**Issue by damlaren** [austinchambers/multiplayer-vr#22]
We have movable "drones" but what we really want is a ship (sub) that moves on player command. Drones may be something that's in the final game, but a movable sub is there for sure.

The Choppa blueprint has some basic code for movement which may be helpful.

**Comment by austinchambers** [comment]
Agreed. I think this one's a priority, but I suppose we first need to get the vessel built (https://github.com/austinchambers/multiplayer-vr/issues/11).

**Comment by damlaren** [comment]
Yeah, it'd be nice to have a sub. But even just being able to move our entire "level" through the sky would be useful; we don't need an actual sub model to test with. My thinking was if you could walk up to a particular screen and possess it to move the "ship" around for now.

**Comment by damlaren** [comment]
I'm editing the submarine test level to work on movement with physics.

As a start I'm putting a camera inside the sub to be able to see from there. I'm following the steps from https://docs.unrealengine.com/latest/INT/Gameplay/HowTo/UsingCameras/Blueprints/index.html to re-assign the default camera for the player. I'll ask later about how to translate the work I'm doing into our existing setup.

Now I've got a cam inside the sub, I'll start working on physics.

**Comment by damlaren** [comment]
Added simple physics for a sub. Players can apply throttle and torque to the sub; the blueprint function "Apply Input Forces" will act on those forces. This way we can separate physics from input.

The current input controls are as follows:

WS: forward/back throttle
AD: left/right throttle
QE: vertical motion
ZC: yaw
up/down keys: pitch
left/right keys: roll

--- Next things to do ---

The sub is currently a pawn. This will be OK for the pilot player so long as they can move their head in VR, but I don't know how to integrate the 2nd player into this setup yet.

Current sub controls are sluggish. Simplifying it and making it feel good will take some experimentation. Something like the UFO template in Unreal will probably feel good.

--- Existing files changed ---
- Input mappings (INI text file)
- Submarine_Test level
- Removed BP_Submarine asset; I did my work in new BP_Sub pawn instead

**Comment by damlaren** [comment]
I tweaked motion so the sub moves decently fast, but still slows down when the player stops applying input.

Getting this exactly right will need playtesting, but at least the sub moves, and the blueprint is written to be input of input mappings.

--- Existing files changed ---
- Input mappings (INI text file)
- BP_Sub blueprint
