### ISSUE TITLE
Add a new MyPlayerstate class. 

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#32]
So we need to use player index to control things, but there's no way to know whether a certain player index corresponds to the current player or not. We need to override the default playerstate class to store this information there.

**Comment by damlaren** [comment]
Can this be closed?

**Comment by damlaren** [comment]
I added custom classes BP_VRGameState (empty) and BP_VRPlayerState (to track kills and deaths). All that's still needed here is storing the player index, if we still need that. I notice there is also a PlayerID field in the PlayerState class, but I don't know if that is good enough for what we need.

**Comment by damlaren** [comment]
Now storing player ID as in issue #92. This is done.
