### ISSUE TITLE
Add a display for weapons status.

### ISSUE THREAD

**Issue by damlaren** [austinchambers/multiplayer-vr#60]
Recharge time for weapons, or how many are left (if we make them depletable), & so on.

**Comment by rameshvarun** [comment]
I can try to do this. It would also be good to have a sound to know when the torpedo has been reloaded.

**Comment by rameshvarun** [comment]
I've added a sound on reload. I would like to add a torpedo icon on the screen that potentially fills up as the torpedo is being loaded. However, I am not sure how best to approach this.

**Comment by damlaren** [comment]
I'm going to change the cooldown to a countdown timer instead of a boolean so it'll be easier to draw in UI. That'll make it easier to draw the 'progress bar' once we figure that out.

**Comment by austinchambers** [comment]
The new status screen using widgets is functional.
