### ISSUE TITLE
Sub won't move

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#67]
1. Start the game in single player mode
2. Press 'W' to move forward. 
   Sub won't move.

**Comment by austinchambers** [comment]
The issue was the "Switch has authority" node that was executing on "Remote" only, meaning that only the client machine can control the movement of it's sub. On single player mode, the player always has authority, so nothing happens.

**Comment by austinchambers** [comment]
This was fixed in 5f2e638. I got the numbering wrong in the commit message.

**Comment by damlaren** [comment]
This was here to solve a problem with throttling up engine volume-- will have to find a better fix for that.

**Comment by damlaren** [comment]
Pushed a fix for this issue that should satisfy both of us.
