### ISSUE TITLE
Think of a better name for our game

### ISSUE THREAD

**Issue by damlaren** [austinchambers/multiplayer-vr#70]
Any suggestions or ideas are welcome.

**Comment by austinchambers** [comment]
How about "Ping?" Ron pointed out how he especially liked how the torpedo did this. Plus, it alludes to the central mechanic: Stealth, Search, and Destroy.

**Comment by damlaren** [comment]
I like this direction, but I'm not sure I'd pick that name. Somehow it doesn't sound ominous enough?

Let's play a game of word association...

Ping
Echoes
Stealth
Search
Destroy
Sub
Deep
Depth (*already the name of a diving-themed game)
Water
Darkness
VR
Sinking
Undersea
...

**Comment by damlaren** [comment]
Silence
Submersion (I kind of like this. It captures what we're doing: replicating the feeling of being submerged in a submarine-- and also sounds like immersion).

**Comment by damlaren** [comment]
Huh. The wikipedia page even mentions a connection: http://en.wikipedia.org/wiki/Immersion_%28virtual_reality%29

**Comment by austinchambers** [comment]
+1 for Submersion

**Comment by wyskim** [comment]
Or how about just its verb form Submerge? 

Some of the other thoughts I had in mind were something like "Into the deep" or like "Deep sea" something but didn't think it completely through. Either way I think it's a cool name!

**Comment by wyskim** [comment]
Or osmething like "The Deep" idk  - maybe that doesn't portray the idea of underwater combat...

**Comment by rameshvarun** [comment]
+1 for Submersion

**Comment by damlaren** [comment]
Submersion is on our title screen.
