### ISSUE TITLE
Targeting reticle for torpedo

### ISSUE THREAD

**Issue by damlaren** [austinchambers/multiplayer-vr#71]
This could be as simple as making travel in the same direction as the little red dot you can see in front of the sub. If not that we should have something drawn to make it easier to aim torpedoes.

**Comment by rameshvarun** [comment]
Currently the red dot is controlled by the VR head tracking, right?

**Comment by damlaren** [comment]
Yes, that is correct.

**Comment by rameshvarun** [comment]
Laser Sight Tutorial - https://www.youtube.com/watch?v=7VaMrs8n8e4

**Comment by damlaren** [comment]
I'll start on this today.

**Comment by damlaren** [comment]
Added a basic reticle. We could do some other fun things with this:
- Draw distance to target next to it
- Color it red if firing a torpedo will damage the boat because target is too close

**Comment by damlaren** [comment]
Pushed another adjustment to its position.
