### ISSUE TITLE
Passive Sonar

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#79]
Passive sonar should exist to help in finding learning about terrain or loud/noisy subs.

Issue is to: 
1. Add a screen to the sub for radar / ping. 
2. Display information about nearby environment

**Comment by damlaren** [comment]
To simplify things, maybe we should just have passive sonar be on all the time and emit no noise?

**Comment by austinchambers** [comment]
To clarify, the original design didn't emit noise. The idea being that the sub would appear less obvious on the other player's screen when passive is turned off. But we can save that for a later enhancement. Updated description.

**Comment by austinchambers** [comment]
Radar via HUD added: 
![image](https://cloud.githubusercontent.com/assets/8466736/6654641/6bb78e14-ca8e-11e4-8838-17e8cbf30798.png)

Looks like it's working fine in multiplayer as well. Still working on projecting it in the world.

**Comment by damlaren** [comment]
That looks really cool!

**Comment by austinchambers** [comment]
It's in 3D now! It's so freaking cool in VR. Given how much this adds in VR, I think we should definitely add depth support. There's also a lot of refinements that need to be made (e.g., material highlighting in a circle light a real radar would and the update interval, etc..), but I wanted to get this out there first. 

![image](https://cloud.githubusercontent.com/assets/8466736/6657927/7ee63b38-cb16-11e4-9f9d-af5d1e570102.png)

**Comment by damlaren** [comment]
Starting to look at sonar code. I am going to make the dots bigger first so they are easier to see.

**Comment by damlaren** [comment]
Made the blips twice as big.

**Comment by damlaren** [comment]
More passive sonar work: objects will be detectable at multiples of a distance "DETECT BASE DISTANCE", based on how much noise they emit. The noise will be set based on what an actor is doing at the moment.

**Comment by damlaren** [comment]
Pushed. Any remaining tweaks for visuals can go into #89.
