### ISSUE TITLE
Primary Vessel Attack

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#8]
Varun demonstrated a great torpedo mechanism. Let's make this our primary attack for the submarine.

**Comment by damlaren** [comment]
Some ideas for weapons:
1. Homing mines (already implemented as BP_Mine) that can be laid by a sub.
2. Homing torpedoes which chase the nearest object implementing the BPI_Targetable interface. This includes mines, and potentially also environmental items like shipwrecks which can distract the torpedo.
3. Unguided torpedoes: these cause more damage and move much faster than a homing torpedo, but only move in a straight line. Some torpedoes can reach speeds of over 200 MPH: http://en.wikipedia.org/wiki/VA-111_Shkval
4. A decoy object that serves to distract other weapons. This might be skippable, as a sub could also lay a mine to distract an incoming torpedo or mine.

All weapons cause radial damage which falls as the distance between a sub and an explosion increases (see BP_Mine for an example).

**Comment by damlaren** [comment]
Torpedoes could also leave trails (using particle effects) which could reveal the location of the firing sub.

**Comment by damlaren** [comment]
Unguided torpedo is implemented.

**Comment by damlaren** [comment]
Closing this, adding separate issue for laying mines
