### ISSUE TITLE
Add input event to turn light on and off

### ISSUE THREAD

**Issue by damlaren** [austinchambers/multiplayer-vr#81]
Looks like this didn't make it to the repository. Map it to a button. Make sure it works in both single-player and multi-player.

**Comment by rameshvarun** [comment]
Currently, it seems like the InteriorLight object is pretty dark / on the outside of the sub. Is it suitable to move this onto the inside / increase brightness?

**Comment by damlaren** [comment]
I actually meant the headlights on the sub. I'm not sure how bright the interior light is, but we don't want it to give away the location of the sub / make it easy to see it.

**Comment by rameshvarun** [comment]
Maybe the button should control all of the lights? Potentially also even the active radar, giving the player one button to "go dark."

**Comment by damlaren** [comment]
That sounds very interesting. We could try that. I think we'll end up only drawing the radar for the client that sees it though.

**Comment by rameshvarun** [comment]
Implemented by 63208b11fd2dadaec5363ab799807b4002e2f208
