### ISSUE TITLE
Networking doesn't function on deployed game. 

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#83]

**Comment by austinchambers** [comment]
c12c077 -- Bypass the Network lobby thing that doesn't work quite right

**Comment by damlaren** [comment]
(Recopied from hangout)

Even single-player is missing the movement and mesh around player. I've been trying different packaging options but no luck so far. The sub mesh is being copied into the package. Dragging sub meshes on their own into the test level shows they get drawn, but the BP_Sub blueprint isn't drawn for some reason. The health screen in the corner is drawn.

**Comment by damlaren** [comment]
I'm also taking a crack at building Unreal Engine from source & then building our game with VS.

**Comment by austinchambers** [comment]
Fixed. I'm still not 100% why this problem didn't occur with the in-editor networking. Still, a lot of player spawning refinement eventually yielded a solution that works. 

Also fixed multiplayer sonar.
