### ISSUE TITLE
Stretch goal: Trails for torpedoes.

### ISSUE THREAD

**Issue by damlaren** [austinchambers/multiplayer-vr#86]
Show a particle trail / streak behind moving torpedoes. This can give away the location of the firing sub and may enhance the underwater look.

**Comment by rameshvarun** [comment]
There was originally a trail, but that seems to have been removed when I migrated the torpedo into this repository. I will look into re-adding it.

**Comment by rameshvarun** [comment]
![image](https://cloud.githubusercontent.com/assets/889879/6660280/248bd9c6-cb53-11e4-81a5-36d9c781ada6.png)
Some problems:
1. The LOD default settings are that the emitter does not emit when out of range. This leads to a strange looking trail.
2. The trail disappears when the torpedo explodes - it should actually stick around for a couple seconds.
3. It doesn't look like bubbles - it looks like steam (what the particle system was initially for).

**Comment by damlaren** [comment]
The steam trails might look passable for Level1 because its very dark.

Looking at how to make trails stick around...

**Comment by damlaren** [comment]
Trail should now stay on after torpedo explodes. Instead of destroying the torpedo when it hits something, I fire off a custom event and destroy all of its components except the particle effect. The trail is destroyed after a 10 second delay.

I'll leave this open in case someone wants to tweak the look of the trail.

**Comment by damlaren** [comment]
_sigh_ The trail also disappears if the torpedo is out of view :( For example, if a torpedo shoots past the submarine.

**Comment by damlaren** [comment]
Ahah! I set a bigger bound so these don't disappear anymore.

**Comment by rameshvarun** [comment]
The particle emitter needs to stop emitting on explode, as currently the emitter continues to bounce around with the same velocity.

**Comment by damlaren** [comment]
Good point.

**Comment by damlaren** [comment]
I removed particle acceleration from the torpedo trail. It spreads out less, so it looks a little less smoky. I also called a function to stop the emitter after an explosion.

**Comment by damlaren** [comment]
Still looks a little smoky, but hopefully there are no bugs left. Closing for now.
