### ISSUE TITLE
Submarines Occasionally Spawn Inside Each Other

### ISSUE THREAD

**Issue by rameshvarun** [austinchambers/multiplayer-vr#88]
When starting the game, on occasion, both submarines will spawn in the same spot, and immediately die.

**Comment by damlaren** [comment]
This is happening a lot for me.

**Comment by austinchambers** [comment]
This was a tricky one. There were multiple problems: 
1. Default pawn was set to "BP_Sub." When this happens, a BP_Sub object is apparently spawned at _any_ player start location. When the server then spawns, it can have a collision. 
2. There was a game mode reference running on the client side. Somehow, in the Multiplayer Shootout demo, the client has a valid instance to game mode. Strange. Anyhow, I stopped doing using the "callback" from the player controller and the problem went away.
