### ISSUE TITLE
Sonar screen and detected items should be more easy to see, especially in lighter areas of the map.

### ISSUE THREAD

**Issue by damlaren** [austinchambers/multiplayer-vr#89]
This makes it hard to see against a light part of the scene. However, placing the sonar screen directly on a black surface (i.e., a screen) would then remove the ability to have limited height detection (something that seems to be low-cost high-value). 

Also, we should remember that if any area in the game is too bright, we are probably doing something wrong. 

I think a combination of: 
1. Making the detected items more emissive. 
   -and-
2. Placing the sonar closer to the sub where it is presently, applying darker materials to the present location, or moving the sonar to another part of the sub.

**Comment by austinchambers** [comment]
Also, is it too hard to notice when your lighting settings are set to "Medium" quality? I worry that things look too dark in preview mode.

**Comment by damlaren** [comment]
Lighting quality does not have any effect.

I do usually work with brightness on my screen turned all the way down, and that is part of it. I do that because turning up brightness gives me headaches. If I crank brightness up really high (70%+) I can read the screen.

I can just barely make out the letters on the screen in VR.

I think the easiest fix for the screen is to put a very weak light in front of it, just to illuminate that.

**Comment by damlaren** [comment]
The new widgets on the left screen remain easy to see in all lighting conditions.

**Comment by damlaren** [comment]
I'm going to see if I can throw it in front of a black background really quick. We can do the 3D depth at a later date if we keep developing the game.

Also, it looks like part of the sonar is sitting inside the front of the sub, or at least, it's impossible to see blips against it.

**Comment by damlaren** [comment]
I think it is easier to see now (although still have double vision problem in VR-- that's for another day.) It is easy to see in all lighting conditions and has a black background now. We can tweak final position for the demo. Closing.
