### ISSUE TITLE
Kill not properly registered when torpedo fired on client machine. 

### ISSUE THREAD

**Issue by austinchambers** [austinchambers/multiplayer-vr#94]

**Comment by austinchambers** [comment]
This was because we set a "shooter" variable to keep track of the person responsible for the torpedo. When we later access it, we try to get the controller for that variable, which was NULL on client machines. 

Here's what I did: 
1. Remove the "shooter" variable entirely. It's redundant because it's already accomplished via the instigator property, which I set when the torpedo was spawned. 
![image](https://cloud.githubusercontent.com/assets/8466736/6680171/fd3352fa-cc10-11e4-9c32-89608313bd7e.png)
1. In the torpedo class, I stopped attempting to get the VR controller. Instead, I accessed the "Instigator" property (available with pawns) and the "Get Instigator Controller" function (also available for pawns). 
   ![image](https://cloud.githubusercontent.com/assets/8466736/6680189/2b6daabc-cc11-11e4-896f-7b5528a74e2c.png)

**Comment by damlaren** [comment]
Maybe I should pull out the old blueprints, but I don't see when the client was running this code? All of this is only running on the authority switch (both spawning torpedoes and applying damage in an explosion). Is this for dedicated server or single player?

**Comment by austinchambers** [comment]
It was with the listen server, using the two player play-in-editor mode, but you may be right. This may not have had to do with the client running code, but instead the way in which the instigator was being kept track of.
